### ISSUE TITLE
老哥，牛逼啊

### ISSUE THREAD

**Issue by plmmanwu** [lvzhihao100/DataBindPercent#1]
点赞

**Comment by lvzhihao100** [comment]
这个库虽然可以解决问题,但是使用的是DataBinding,在xml布局中,一旦某个地方写错,编译器就会报一堆的错误,很难找到真正的出错点.给你推荐一个更完美的库,https://github.com/Firedamp/Rudeness 
你可以研究一下,这个才是真牛!
